services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio:/data
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio: {}
