- name: config directory
  file:
    path: /etc/docker
    mode: '0755'
    owner: root
    group: root
    state: directory
- name: config file
  copy:
    dest: /etc/docker/daemon.json
    src: docker-daemon.json
    owner: root
    group: root
    mode: '0644'
