name: ansible-lint
on:
  pull_request: {}
jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@main
        with:
          working_directory: ansible
