name: ansible-lint
on:
  push:
    branches-ignore: [main, gh-pages]
    paths:
      - ansible
jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@main
        with:
          args: "ansible/site.yml"
