name: ansible-lint
on:
  push:
    branches-ignore: [main, gh-pages]
    paths:
      - ansible
  workflow_dispatch:

jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ansible/ansible-lint@262624cd0ab22a4221293216856c59671ce7aa5e # v26.6.0
        with:
          args: "ansible/site.yml"
