name: main

on:
  push:
    branches: [main, duplicate-page]

permissions:
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: prepare
      run: "sudo apt update && sudo apt install -y libsnappy-dev liblzo2-dev"
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[ext]"
    - uses: wtnb75/actions/flake8@main
    - uses: wtnb75/actions/pytest@main
    - uses: wtnb75/actions/wheel@main
    - uses: wtnb75/actions/merge-pages@main
      with:
        dirs: cover
        #pydist: dist
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: deploy pages
      uses: actions/deploy-pages@v4
      id: deployment
    - uses: wtnb75/actions/docker@main
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
