name: tag

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v4
      with:
        path: _cache
        key: ${{ runner.os }}-pip-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pip-
    - name: prepare
      run: "sudo apt update && sudo apt install -y libsnappy-dev liblzo2-dev"
    - name: versioning
      run: "echo \"VERSION = '${GITHUB_REF##*/v}'\" > log2s3/version.py"
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[ext,test] --cache-dir _cache"
    - uses: wtnb75/actions/ruff@main
    - uses: wtnb75/actions/pytest@main
    - id: wheel
      uses: wtnb75/actions/wheel@main
    - id: pdoc
      uses: wtnb75/actions/pdoc@main
      with:
        output-dir: docs
        module: log2s3
    - uses: docker/setup-qemu-action@v3
    - uses: ./.github/actions/pipcache
    - uses: wtnb75/actions/docker@main
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
    - uses: wtnb75/actions/pypi-upload@main
      with:
        username: ${{ secrets.TWINE_USERNAME }}
        password: ${{ secrets.TWINE_PASSWORD }}
        file: dist/${{ steps.wheel.outputs.filename }}
